resources:
  limits:
    cpus: 2.0
    memory: 4096

lms:
  additional_envs: []

network:
  web_port:
    port_number: 9000
    container_port: 9000
    bind_mode: published
  cli_port:
    port_number: 9090
    container_port: 9090
    bind_mode: published

run_as:
  user: 568
  group: 568

ix_volumes:
  config: /mnt/storage/lms/config
  music: /mnt/storage/lms/music
  playlist: /mnt/storage/lms/playlist

storage:
  config:
    type: ix_volume
    ix_volume_config:
      dataset_name: config
      create_host_path: true
  music:
    type: ix_volume
    ix_volume_config:
      dataset_name: music
      create_host_path: true
  playlist:
    type: ix_volume
    ix_volume_config:
      dataset_name: playlist
      create_host_path: true
  additional_storage: []
