app_version: 9.0.0
capabilities: []
categories:
- media
- entertainment
description: Lyrion Music Server - controls a wide range of Squeezebox audio players
home: https://lyrion.org/
host_mounts: []
icon: https://avatars.githubusercontent.com/u/138057124?s=200&v=4
keywords:
- media
- entertainment
- music
- streaming
lib_version: 2.1.7
lib_version_hash: c4c34d5b8aa0e8c3016b7cb3ee8a78ef09d4ffe80f34eb35107810656a43a615
maintainers:
- email: dev@ixsystems.com
  name: truenas
  url: https://www.truenas.com/
name: lyrion-music-server
run_as_context:
- description: LMS runs as any non-root user
  gid: 568
  group_name: lms
  uid: 568
  user_name: lms
sources:
- https://github.com/lms-community/slimserver
title: Lyrion Music Server
train: community
version: 1.0.0
