resources:
  limits:
    cpus: 2.0
    memory: 8192

hostname: localhost

gitlab:
  root_password: blortblort
  additional_envs:

network:
  web_port: 8765
  ssh_port: 2222

ix_volumes:
  config: /mnt/storage/gitlab/config
  data: /mnt/storage/gitlab/data
  logs: /mnt/storage/gitlab/logs

storage:
  config:
    type: ix_volume
    ix_volume_config:
      dataset_name: config
      create_host_path: true
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  logs:
    type: ix_volume
    ix_volume_config:
      dataset_name: logs
      create_host_path: true
  additional_storage: []
