app_version: 17.7.0-ce
capabilities: []
categories:
- productivity
description: GitLab -- an open source software development platform, community edition
home: https://gitlab.com
host_mounts: []
icon: https://TODO
keywords:
- git
- gitlab
- source control
lib_version: 2.1.7
lib_version_hash: c4c34d5b8aa0e8c3016b7cb3ee8a78ef09d4ffe80f34eb35107810656a43a615
maintainers:
- email: hartzell@alerce.com
  name: George Hartzell
  url: https://github.com/hartzell
name: gitlab-ce
run_as_context:
- description: Gitlab runs as non-root user.
  gid: 568
  group_name: apps
  uid: 568
  user_name: apps
screenshots:
- https://TODO
sources:
- https://gitlab.com/gitlab-org/gitlab
title: GitLab Community Edition
train: community
version: 1.0.0
